sudo: required
services:
  - docker

before_install:
  - docker build -t ivane-gkomarteli/docker-react -f Dockerfile.dev .

script:
  - docker run ivane-gkomarteli/docker-react npm run test -- --coverage